package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Banner generated by hbm2java
 */
@Entity
@Table(name="Banner"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class Banner  implements java.io.Serializable {


     private int bannerId;
     private String bannerName;
     private String imageLink;
     private int prioritys;
     private boolean bannerStatus;

    public Banner() {
    }

    public Banner(int bannerId, String bannerName, String imageLink, int prioritys, boolean bannerStatus) {
       this.bannerId = bannerId;
       this.bannerName = bannerName;
       this.imageLink = imageLink;
       this.prioritys = prioritys;
       this.bannerStatus = bannerStatus;
    }
   
     @Id 

    
    @Column(name="BannerId", unique=true, nullable=false)
    public int getBannerId() {
        return this.bannerId;
    }
    
    public void setBannerId(int bannerId) {
        this.bannerId = bannerId;
    }

    
    @Column(name="BannerName", nullable=false)
    public String getBannerName() {
        return this.bannerName;
    }
    
    public void setBannerName(String bannerName) {
        this.bannerName = bannerName;
    }

    
    @Column(name="ImageLink", nullable=false)
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }

    
    @Column(name="Prioritys", nullable=false)
    public int getPrioritys() {
        return this.prioritys;
    }
    
    public void setPrioritys(int prioritys) {
        this.prioritys = prioritys;
    }

    
    @Column(name="BannerStatus", nullable=false)
    public boolean isBannerStatus() {
        return this.bannerStatus;
    }
    
    public void setBannerStatus(boolean bannerStatus) {
        this.bannerStatus = bannerStatus;
    }




}


