package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name="Blog"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class Blog  implements java.io.Serializable {


     private int blogId;
     private String blogName;
     private String content;
     private Date created;
     private boolean blogStatus;
     private String imageLink;

    public Blog() {
    }

    public Blog(int blogId, String blogName, String content, Date created, boolean blogStatus, String imageLink) {
       this.blogId = blogId;
       this.blogName = blogName;
       this.content = content;
       this.created = created;
       this.blogStatus = blogStatus;
       this.imageLink = imageLink;
    }
   
     @Id 

    
    @Column(name="BlogId", unique=true, nullable=false)
    public int getBlogId() {
        return this.blogId;
    }
    
    public void setBlogId(int blogId) {
        this.blogId = blogId;
    }

    
    @Column(name="BlogName", nullable=false)
    public String getBlogName() {
        return this.blogName;
    }
    
    public void setBlogName(String blogName) {
        this.blogName = blogName;
    }

    
    @Column(name="Content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created", nullable=false, length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="BlogStatus", nullable=false)
    public boolean isBlogStatus() {
        return this.blogStatus;
    }
    
    public void setBlogStatus(boolean blogStatus) {
        this.blogStatus = blogStatus;
    }

    
    @Column(name="imageLink", nullable=false)
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }




}


