package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="Categories"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class Categories  implements java.io.Serializable {


     private int cateId;
     private String cateName;
     private String cateTitle;
     private int prioritys;
     private boolean cateStatus;
     private Set<Product> products = new HashSet<Product>(0);

    public Categories() {
    }

	
    public Categories(int cateId, String cateName, String cateTitle, int prioritys, boolean cateStatus) {
        this.cateId = cateId;
        this.cateName = cateName;
        this.cateTitle = cateTitle;
        this.prioritys = prioritys;
        this.cateStatus = cateStatus;
    }
    public Categories(int cateId, String cateName, String cateTitle, int prioritys, boolean cateStatus, Set<Product> products) {
       this.cateId = cateId;
       this.cateName = cateName;
       this.cateTitle = cateTitle;
       this.prioritys = prioritys;
       this.cateStatus = cateStatus;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="CateId", unique=true, nullable=false)
    public int getCateId() {
        return this.cateId;
    }
    
    public void setCateId(int cateId) {
        this.cateId = cateId;
    }

    
    @Column(name="CateName", nullable=false)
    public String getCateName() {
        return this.cateName;
    }
    
    public void setCateName(String cateName) {
        this.cateName = cateName;
    }

    
    @Column(name="CateTitle", nullable=false)
    public String getCateTitle() {
        return this.cateTitle;
    }
    
    public void setCateTitle(String cateTitle) {
        this.cateTitle = cateTitle;
    }

    
    @Column(name="Prioritys", nullable=false)
    public int getPrioritys() {
        return this.prioritys;
    }
    
    public void setPrioritys(int prioritys) {
        this.prioritys = prioritys;
    }

    
    @Column(name="CateStatus", nullable=false)
    public boolean isCateStatus() {
        return this.cateStatus;
    }
    
    public void setCateStatus(boolean cateStatus) {
        this.cateStatus = cateStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categories")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


