package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name="Comment"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class Comment  implements java.io.Serializable {


     private int commentId;
     private Product product;
     private Users users;
     private int parentId;
     private boolean commentStatus;
     private String content;

    public Comment() {
    }

    public Comment(int commentId, Product product, Users users, int parentId, boolean commentStatus, String content) {
       this.commentId = commentId;
       this.product = product;
       this.users = users;
       this.parentId = parentId;
       this.commentStatus = commentStatus;
       this.content = content;
    }

    public Comment(Product product, Users users, int parentId, boolean commentStatus, String content) {
        this.product = product;
        this.users = users;
        this.parentId = parentId;
        this.commentStatus = commentStatus;
        this.content = content;
    }
    
   
     @Id 

    
    @Column(name="CommentId", unique=true, nullable=false)
    public int getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(int commentId) {
        this.commentId = commentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProdId", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UserId", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="ParentId", nullable=false)
    public int getParentId() {
        return this.parentId;
    }
    
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    
    @Column(name="CommentStatus", nullable=false)
    public boolean isCommentStatus() {
        return this.commentStatus;
    }
    
    public void setCommentStatus(boolean commentStatus) {
        this.commentStatus = commentStatus;
    }

    
    @Column(name="Content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


