package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="Contact"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class Contact  implements java.io.Serializable {


     private int id;
     private String email;
     private String phone;
     private String contactAddress;

    public Contact() {
    }

    public Contact(int id, String email, String phone, String contactAddress) {
       this.id = id;
       this.email = email;
       this.phone = phone;
       this.contactAddress = contactAddress;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Phone", nullable=false)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="ContactAddress", nullable=false)
    public String getContactAddress() {
        return this.contactAddress;
    }
    
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }




}


