package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImageProduct generated by hbm2java
 */
@Entity
@Table(name="ImageProduct"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class ImageProduct  implements java.io.Serializable {


     private int imageId;
     private Product product;
     private String imageLink;

    public ImageProduct() {
    }

    public ImageProduct(int imageId, Product product, String imageLink) {
       this.imageId = imageId;
       this.product = product;
       this.imageLink = imageLink;
    }
   
     @Id 

    
    @Column(name="ImageId", unique=true, nullable=false)
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProdId", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="ImageLink", nullable=false)
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }




}


