package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="Orders"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class Orders  implements java.io.Serializable {


     private int orderId;
     private Users users;
     private Date created;
     private double totalAmount;
     private String orderStatus;
     private String phone;
     private String email;
     private String orderAddress;
     private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public Orders() {
    }

	
    public Orders(int orderId, Users users, Date created, double totalAmount, String orderStatus, String phone, String email, String orderAddress) {
        this.orderId = orderId;
        this.users = users;
        this.created = created;
        this.totalAmount = totalAmount;
        this.orderStatus = orderStatus;
        this.phone = phone;
        this.email = email;
        this.orderAddress = orderAddress;
    }
    public Orders(int orderId, Users users, Date created, double totalAmount, String orderStatus, String phone, String email, String orderAddress, Set<OrderDetail> orderDetails) {
       this.orderId = orderId;
       this.users = users;
       this.created = created;
       this.totalAmount = totalAmount;
       this.orderStatus = orderStatus;
       this.phone = phone;
       this.email = email;
       this.orderAddress = orderAddress;
       this.orderDetails = orderDetails;
    }
   
     @Id 

    
    @Column(name="OrderId", unique=true, nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UserId", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created", nullable=false, length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="TotalAmount", nullable=false, precision=53, scale=0)
    public double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    
    @Column(name="OrderStatus", nullable=false)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    
    @Column(name="Phone", nullable=false)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="Email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="OrderAddress", nullable=false)
    public String getOrderAddress() {
        return this.orderAddress;
    }
    
    public void setOrderAddress(String orderAddress) {
        this.orderAddress = orderAddress;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }





}


