package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name="OrderDetail"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class OrderDetail  implements java.io.Serializable {


     private OrderDetailId id;
     private Orders orders;
     private Product product;
     private int quantity;
     private double amount;
     private double discount;

    public OrderDetail() {
    }

    public OrderDetail(OrderDetailId id, Orders orders, Product product, int quantity, double amount, double discount) {
       this.id = id;
       this.orders = orders;
       this.product = product;
       this.quantity = quantity;
       this.amount = amount;
       this.discount = discount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="OrderId", nullable=false) ), 
        @AttributeOverride(name="prodId", column=@Column(name="ProdId", nullable=false) ) } )
    public OrderDetailId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OrderId", nullable=false, insertable=false, updatable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProdId", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="Amount", nullable=false, precision=53, scale=0)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    
    @Column(name="Discount", nullable=false, precision=53, scale=0)
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }




}


