package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId  implements java.io.Serializable {


     private int orderId;
     private int prodId;

    public OrderDetailId() {
    }

    public OrderDetailId(int orderId, int prodId) {
       this.orderId = orderId;
       this.prodId = prodId;
    }
   


    @Column(name="OrderId", nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }


    @Column(name="ProdId", nullable=false)
    public int getProdId() {
        return this.prodId;
    }
    
    public void setProdId(int prodId) {
        this.prodId = prodId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderDetailId) ) return false;
		 OrderDetailId castOther = ( OrderDetailId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getProdId()==castOther.getProdId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getProdId();
         return result;
   }   


}


