package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="Product"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class Product  implements java.io.Serializable {


     private int prodId;
     private Categories categories;
     private String prodName;
     private double price;
     private String title;
     private String descriptions;
     private String imageLink;
     private Date created;
     private double discount;
     private boolean prodStatus;
     private Set<ImageProduct> imageProducts = new HashSet<ImageProduct>(0);
     private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<Star> stars = new HashSet<Star>(0);

    public Product() {
    }

	
    public Product(int prodId, Categories categories, String prodName, double price, String title, String descriptions, Date created, double discount, boolean prodStatus) {
        this.prodId = prodId;
        this.categories = categories;
        this.prodName = prodName;
        this.price = price;
        this.title = title;
        this.descriptions = descriptions;
        this.created = created;
        this.discount = discount;
        this.prodStatus = prodStatus;
    }
    public Product(int prodId, Categories categories, String prodName, double price, String title, String descriptions, String imageLink, Date created, double discount, boolean prodStatus, Set<ImageProduct> imageProducts, Set<OrderDetail> orderDetails, Set<Comment> comments, Set<Star> stars) {
       this.prodId = prodId;
       this.categories = categories;
       this.prodName = prodName;
       this.price = price;
       this.title = title;
       this.descriptions = descriptions;
       this.imageLink = imageLink;
       this.created = created;
       this.discount = discount;
       this.prodStatus = prodStatus;
       this.imageProducts = imageProducts;
       this.orderDetails = orderDetails;
       this.comments = comments;
       this.stars = stars;
    }
   
     @Id 

    
    @Column(name="ProdId", unique=true, nullable=false)
    public int getProdId() {
        return this.prodId;
    }
    
    public void setProdId(int prodId) {
        this.prodId = prodId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CateId", nullable=false)
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    
    @Column(name="ProdName", nullable=false)
    public String getProdName() {
        return this.prodName;
    }
    
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    
    @Column(name="Price", nullable=false, precision=53, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="Title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="Descriptions", nullable=false)
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }

    
    @Column(name="ImageLink")
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created", nullable=false, length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="Discount", nullable=false, precision=53, scale=0)
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }

    
    @Column(name="ProdStatus", nullable=false)
    public boolean isProdStatus() {
        return this.prodStatus;
    }
    
    public void setProdStatus(boolean prodStatus) {
        this.prodStatus = prodStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<ImageProduct> getImageProducts() {
        return this.imageProducts;
    }
    
    public void setImageProducts(Set<ImageProduct> imageProducts) {
        this.imageProducts = imageProducts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Star> getStars() {
        return this.stars;
    }
    
    public void setStars(Set<Star> stars) {
        this.stars = stars;
    }




}


