package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Star generated by hbm2java
 */
@Entity
@Table(name="Star"
    ,schema="dbo"
    ,catalog="WebOgani"
)
public class Star  implements java.io.Serializable {


     private StarId id;
     private Product product;
     private Users users;
     private int mark;

    public Star() {
    }

    public Star(StarId id, Product product, Users users, int mark) {
       this.id = id;
       this.product = product;
       this.users = users;
       this.mark = mark;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="prodId", column=@Column(name="ProdId", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="UserId", nullable=false) ) } )
    public StarId getId() {
        return this.id;
    }
    
    public void setId(StarId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProdId", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UserId", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="Mark", nullable=false)
    public int getMark() {
        return this.mark;
    }
    
    public void setMark(int mark) {
        this.mark = mark;
    }




}


