package ogani.entity;
// Generated Oct 31, 2020 11:45:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StarId generated by hbm2java
 */
@Embeddable
public class StarId  implements java.io.Serializable {


     private int prodId;
     private int userId;

    public StarId() {
    }

    public StarId(int prodId, int userId) {
       this.prodId = prodId;
       this.userId = userId;
    }
   


    @Column(name="ProdId", nullable=false)
    public int getProdId() {
        return this.prodId;
    }
    
    public void setProdId(int prodId) {
        this.prodId = prodId;
    }


    @Column(name="UserId", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StarId) ) return false;
		 StarId castOther = ( StarId ) other; 
         
		 return (this.getProdId()==castOther.getProdId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProdId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


